# Generated by Django 4.1.7 on 2023-07-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='digital',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
