# Generated by Django 4.1.7 on 2023-07-03 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_cart_cartitem_flower_delete_fooditem_cartitem_flower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='product_available',
        ),
    ]
